# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 10 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Service Worker files
  manifest:
    - "src/manifest.json"
  sw:
    - "src/sw.js"
  # Paths to static assets that aren't images, CSS, or JavaScript
  fonts:
  - "src/assets/fonts/*"
  favicon:
  - "src/favicon.ico"
  assets:
    - "src/assets/fonts/*"
    - "!src/assets/scss/{**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "src/assets/scss"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/*"
BUILDERS:
  components:
  - id: blog
    brands:
    - iberojet
